# Use postgres/example user/password credentials
version: '3.1'

services:
  php-fpm:
    container_name: payslip_php
    build:
      context: ./php
    depends_on:
      - db
    volumes:
      - ../:/var/www/
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    environment:
      PHP_IDE_CONFIG: "serverName=PAYSLIP"

  db:
    image: postgres
    container_name: payslip_pgsql
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: admin123
      POSTGRES_DATABASE: payslip

  adminer:
    container_name: payslip_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    container_name: payslip_nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
